apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-boot-kubernetes-example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes-example
    spec:
      containers:
        - name: spring-boot-kubernetes-example
          image: 'gcr.io/bold-site-315415/spring-boot-kubernetes-example:v1'
          ports:
              - containerPort: 8080 